#!/usr/bin/env node
/**
 * @cq/tokens build pipeline.
 *
 * ONE structured token source (src/*.ts) -> THREE emitted artifacts:
 *   dist/index.js   + dist/index.d.ts   — compiled typed TS exports (via tsc)
 *   dist/tokens.css                     — CSS custom properties (--cq-*)
 *   dist/theme.css                      — a Tailwind v4 @theme block
 *
 * IDEMPOTENT by construction (check T2): the output is a pure function of the
 * source. No Date.now(), no build id, no absolute paths in any emitted
 * artifact; object keys are walked in an explicit, stable order. Running the
 * build twice yields byte-identical artifacts.
 *
 * The CSS artifacts are generated by importing the freshly-compiled
 * dist/index.js, so they cannot drift from the typed source.
 */

import { execFileSync } from "node:child_process";
import { rmSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const PKG_DIR = join(SCRIPT_DIR, "..");
const DIST = join(PKG_DIR, "dist");

/* ── 1. Clean + compile the TS source to dist/ (index.js + index.d.ts). ───── */
rmSync(DIST, { recursive: true, force: true });
mkdirSync(DIST, { recursive: true });

// tsc is resolved from the repo's node_modules (hoisted by npm workspaces).
execFileSync(
  process.execPath,
  [join(PKG_DIR, "..", "..", "node_modules", "typescript", "bin", "tsc"), "-p", "tsconfig.json"],
  { cwd: PKG_DIR, stdio: "inherit" }
);

/* ── 2. Import the just-built module — single source for the CSS artifacts. ─ */
const mod = await import(pathToFileURL(join(DIST, "index.js")).href);
const {
  spacing,
  spacingScale,
  typeScale,
  typeScaleOrder,
  lineHeight,
  tracking,
  fontWeight,
  fontFamily,
  color,
  colorOrder,
  colorThemeName,
  radius,
  radiusOrder,
  shadow,
  shadowOrder,
  duration,
  durationOrder,
  easingCss,
  easingOrder,
  breakpoint,
  breakpointOrder,
  zIndex,
  zIndexOrder,
} = mod;

/* ── helpers — stable, deterministic emit ────────────────────────────────── */
const HEADER = [
  "/* AUTO-GENERATED by @cq/tokens — packages/tokens/scripts/build.mjs.",
  "   Source of truth: packages/tokens/src/*.ts. Do not edit by hand. */",
].join("\n");

/** Render a list of `  --name: value;` declarations. */
const decls = (pairs) =>
  pairs.map(([name, value]) => `  ${name}: ${value};`).join("\n");

/* ── 3. dist/tokens.css — plain CSS custom properties under :root. ───────── */
const tokenVarPairs = [];
// spacing
for (const k of spacingScale) tokenVarPairs.push([`--cq-space-${k}`, spacing[k]]);
// type scale (font sizes)
for (const k of typeScaleOrder) tokenVarPairs.push([`--cq-text-${k}`, typeScale[k]]);
// line-height
for (const k of Object.keys(lineHeight)) tokenVarPairs.push([`--cq-leading-${k}`, lineHeight[k]]);
// tracking
for (const k of Object.keys(tracking)) tokenVarPairs.push([`--cq-tracking-${k}`, tracking[k]]);
// font weight
for (const k of Object.keys(fontWeight)) tokenVarPairs.push([`--cq-weight-${k}`, fontWeight[k]]);
// font family
for (const k of Object.keys(fontFamily)) tokenVarPairs.push([`--cq-font-${k}`, fontFamily[k]]);
// color — raw HSL triplet, byte-identical to globals.css :root
for (const k of colorOrder) {
  tokenVarPairs.push([`--cq-color-${colorThemeName[k]}`, color[k].hsl]);
}
// radius
for (const k of radiusOrder) tokenVarPairs.push([`--cq-radius-${k}`, radius[k]]);
// shadow
for (const k of shadowOrder) tokenVarPairs.push([`--cq-shadow-${k}`, shadow[k]]);
// motion — durations (in ms for CSS) + easing curves
for (const k of durationOrder) {
  tokenVarPairs.push([`--cq-duration-${k}`, `${Math.round(duration[k] * 1000)}ms`]);
}
for (const k of easingOrder) tokenVarPairs.push([`--cq-ease-${k}`, easingCss[k]]);
// breakpoint
for (const k of breakpointOrder) tokenVarPairs.push([`--cq-screen-${k}`, breakpoint[k]]);
// z-index
for (const k of zIndexOrder) tokenVarPairs.push([`--cq-z-${k}`, String(zIndex[k])]);

const tokensCss = `${HEADER}\n\n:root {\n${decls(tokenVarPairs)}\n}\n`;
writeFileSync(join(DIST, "tokens.css"), tokensCss, "utf8");

/* ── 4. dist/theme.css — a Tailwind v4 @theme block. ─────────────────────── */
/* Tailwind v4 reads `@theme { --color-* / --text-* / --spacing-* … }` to
   generate utilities. These mirror the same token source. The live app keeps
   its hand-written `@theme inline` in globals.css (byte-locked); this artifact
   is the generated equivalent — additively importable (e.g. by Storybook) and
   a proof that the token source can drive a Tailwind theme. */
const themePairs = [];
// colors -> Tailwind --color-* (composed from the --cq-color-* triplet vars)
for (const k of colorOrder) {
  const name = colorThemeName[k];
  themePairs.push([`--color-${name}`, `hsl(var(--cq-color-${name}))`]);
}
// font families
for (const k of Object.keys(fontFamily)) {
  themePairs.push([`--font-${k}`, `var(--cq-font-${k})`]);
}
// type scale -> Tailwind --text-*
for (const k of typeScaleOrder) {
  themePairs.push([`--text-${k}`, `var(--cq-text-${k})`]);
}
// spacing -> Tailwind --spacing-* (named scale; coexists with the numeric one)
for (const k of spacingScale) {
  themePairs.push([`--spacing-${k}`, `var(--cq-space-${k})`]);
}
// radius -> Tailwind --radius-*
for (const k of radiusOrder) {
  themePairs.push([`--radius-${k}`, `var(--cq-radius-${k})`]);
}
// shadow -> Tailwind --shadow-*
for (const k of shadowOrder) {
  themePairs.push([`--shadow-${k}`, `var(--cq-shadow-${k})`]);
}
// easing -> Tailwind --ease-*
for (const k of easingOrder) {
  themePairs.push([`--ease-${k}`, `var(--cq-ease-${k})`]);
}
// breakpoints -> Tailwind --breakpoint-*
for (const k of breakpointOrder) {
  themePairs.push([`--breakpoint-${k}`, `var(--cq-screen-${k})`]);
}

const themeCss =
  `${HEADER}\n\n` +
  `/* The generated Tailwind v4 theme — mirrors packages/tokens/src.\n` +
  `   Import AFTER \`@import "tailwindcss"\` and AFTER tokens.css. */\n` +
  `@theme {\n${decls(themePairs)}\n}\n`;
writeFileSync(join(DIST, "theme.css"), themeCss, "utf8");

/* ── done. ───────────────────────────────────────────────────────────────── */
console.log(
  `[@cq/tokens] built: dist/index.js, dist/index.d.ts, dist/tokens.css ` +
    `(${tokenVarPairs.length} vars), dist/theme.css (${themePairs.length} theme tokens)`
);
